<a href="https://colab.research.google.com/github/katiyardivyanshu08-bit/Retail_Pulse_Project_/blob/main/1_Retail_data_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')
# Getting access
# from google.colab import drive
# drive.mount('/content/drive')

In [26]:
url = "https://raw.githubusercontent.com/katiyardivyanshu08-bit/Retail_Pulse_Project_/main/Data/RetailPulse_500000_rows.csv"
df = pd.read_csv(url)
df.shape #(801600, 13)
df.head(10)
df.tail()
df.sample(10)

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
415671,472722,45,Other,South,Clothing,52308.22,9.0,9304.51,2025-12-28,2.83,0.6030,0.0807,Regular
163543,471409,49,Male,East,Sports,62416.98,7.0,31497.47,2025-12-13,4.45,0.1590,0.0561,Regular
285327,596200,45,Male,West,Beauty,18000.00,4.0,3001.09,2025-11-30,2.25,0.2355,0.0210,Budget
26941,213668,36,Male,South,Grocery,34739.60,4.0,6413.18,2025-10-11,4.15,0.2997,0.0664,Budget
361852,411638,25,Female,East,Electronics,89954.48,10.0,19186.38,2025-12-30,6.68,0.4876,0.0696,Premium
74368,356689,41,Female,East,Clothing,61942.76,7.0,8546.19,2025-11-19,8.15,0.2169,0.0656,Regular
278759,203232,26,Female,North,Clothing,29974.98,1.0,3331.94,2025-11-15,6.80,0.4254,0.0601,Budget
190728,307577,45,Male,North,ELECTRONICS,64001.38,6.0,14329.35,2025-11-22,5.19,0.2085,0.0186,Regular
109773,215288,32,Male,Central,Clothing,87203.06,28.0,23264.27,2025-12-30,6.19,0.0252,0.1087,Premium
137165,588112,26,Male,North,Home & Kitchen,23858.51,9.0,7197.20,2025-08-15,4.99,0.4411,0.0567,Budget

In [27]:
df["LastPurchaseDate"] = pd.to_datetime(
    df["LastPurchaseDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            500000 non-null  int64
 1   Age                   500000 non-null  int64
 2   Gender                497001 non-null  object
 3   Region                496504 non-null  object
 4   ProductCategory       497001 non-null  object
 5   AnnualIncome          495002 non-null  float64
 6   PurchaseFrequency     495998 non-null  float64
 7   AnnualPurchaseAmount  500000 non-null  float64
 8   LastPurchaseDate      500000 non-null  datetime64[ns]
 9   CustomerTenure        500000 non-null  float64
 10  DiscountUsage         494997 non-null  float64
 11  ReturnRate            496500 non-null  float64
 12  CustomerSegment       500000 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 49.6+ MB

In [29]:
df.describe()

,CustomerID,Age,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate
count,500000.000000,500000.000000,495002.000000,495998.000000,500000.000000,500000,500000.000000,494997.000000,496500.000000
mean,349499.546422,40.856144,67404.824695,8.596408,12884.542060,2025-11-01 10:31:07.564800256,4.243120,0.339433,0.085718
min,100001.000000,18.000000,18000.000000,1.000000,565.000000,2024-12-31 00:00:00,0.250000,0.005100,0.000000
25%,224736.750000,32.000000,43434.195000,5.000000,6763.360000,2025-10-15 00:00:00,2.270000,0.187200,0.049700
50%,349483.500000,40.000000,60097.425000,7.000000,10392.100000,2025-11-21 00:00:00,3.700000,0.309500,0.075800
75%,474260.250000,49.000000,83034.477500,11.000000,16047.522500,2025-12-12 00:00:00,5.640000,0.466800,0.111600
max,599000.000000,70.000000,350000.000000,55.000000,316973.080000,2025-12-30 00:00:00,14.800000,0.980000,0.524700
std,144051.571449,11.756830,34246.285517,5.554789,9422.420371,NaN,2.646383,0.190285,0.049652

In [30]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Region', 'ProductCategory',
       'AnnualIncome', 'PurchaseFrequency', 'AnnualPurchaseAmount',
       'LastPurchaseDate', 'CustomerTenure', 'DiscountUsage', 'ReturnRate',
       'CustomerSegment'],
      dtype='object')

In [31]:
num=df.select_dtypes(include="number").columns
cat=df.select_dtypes(include="object").columns
print(num)
print(cat)

Index(['CustomerID', 'Age', 'AnnualIncome', 'PurchaseFrequency',
       'AnnualPurchaseAmount', 'CustomerTenure', 'DiscountUsage',
       'ReturnRate'],
      dtype='object')
Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

**Numerical Column**

In [32]:
# df.isnull().mean()*100
df.select_dtypes(include="number").isnull().sum()

CustomerID                 0
Age                        0
AnnualIncome            4998
PurchaseFrequency       4002
AnnualPurchaseAmount       0
CustomerTenure             0
DiscountUsage           5003
ReturnRate              3500
dtype: int64

In [33]:
null_count=df.select_dtypes(include=["number"]).isnull().sum()
null_count[null_count>0]

AnnualIncome         4998
PurchaseFrequency    4002
DiscountUsage        5003
ReturnRate           3500
dtype: int64

**Categorical**

In [34]:
cat

Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

In [35]:
df.select_dtypes(include="object").isnull().sum()

Gender             2999
Region             3496
ProductCategory    2999
CustomerSegment       0
dtype: int64

In [36]:
null_count=df.select_dtypes(include=["object"]).isnull().sum()
null_count[null_count>0]

Gender             2999
Region             3496
ProductCategory    2999
dtype: int64

In [37]:
df["Gender"].unique()

array(['Male', 'Female', nan, 'Other'], dtype=object)

In [38]:
for col in cat:
    df[col] = df[col].str.strip().str.lower()

In [39]:
df["Gender"] = df["Gender"].replace("other", "unknown")

In [40]:
df["Region"].unique()

array(['north', 'east', 'central', 'south', 'west', nan], dtype=object)

In [41]:
df["ProductCategory"].unique()

array(['beauty', 'clothing', 'electronics', 'home & kitchen', 'grocery',
       'sports', nan, 'home and kitchen'], dtype=object)

In [42]:
df["ProductCategory"] = df["ProductCategory"].replace({
    "home and kitchen": "home & kitchen"
})

In [43]:
df["CustomerSegment"].unique()

array(['regular', 'budget', 'premium'], dtype=object)

**Duplicate**

In [44]:
# df.duplicated().sum()  #1000
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499000 entries, 0 to 498999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            499000 non-null  int64
 1   Age                   499000 non-null  int64
 2   Gender                496006 non-null  object
 3   Region                495507 non-null  object
 4   ProductCategory       496006 non-null  object
 5   AnnualIncome          494010 non-null  float64
 6   PurchaseFrequency     495008 non-null  float64
 7   AnnualPurchaseAmount  499000 non-null  float64
 8   LastPurchaseDate      499000 non-null  datetime64[ns]
 9   CustomerTenure        499000 non-null  float64
 10  DiscountUsage         494010 non-null  float64
 11  ReturnRate            495507 non-null  float64
 12  CustomerSegment       499000 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 49.5+ MB

In [46]:
df

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
0,204242,50,male,north,beauty,57328.90,4.0,10206.51,2025-09-07,3.16,0.3790,0.0929,regular
1,299677,36,male,east,clothing,66674.05,1.0,5497.05,2025-11-05,7.11,0.2153,0.0251,regular
2,240200,37,male,central,electronics,39673.95,2.0,5850.72,2025-10-20,6.43,0.1474,0.1273,budget
3,232815,36,male,south,clothing,70271.46,11.0,10174.37,2025-12-01,2.50,0.1379,0.0133,regular
4,508698,30,female,west,home & kitchen,67653.56,6.0,10441.58,2025-12-30,3.21,0.0958,0.0853,regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...
498995,359179,49,male,east,home & kitchen,64805.16,7.0,8624.35,2025-11-06,2.85,0.3288,0.1329,regular
498996,465839,33,male,central,electronics,100903.39,4.0,10645.11,2025-10-26,5.34,0.1384,0.0431,regular
498997,231933,33,male,central,home & kitchen,46207.75,7.0,9266.84,2025-12-30,9.19,0.5072,0.0686,regular
498998,246868,51,male,south,home & kitchen,36892.09,3.0,4569.21,2025-10-26,5.49,0.3177,0.1984,regular
498999,221959,29,female,south,beauty,84832.95,5.0,9945.71,2024-12-31,2.97,0.0733,0.0344,budget

In [47]:
# df.to_csv("After_clean_retailpulse.csv", index=False)