<a href="https://colab.research.google.com/github/katiyardivyanshu08-bit/Retail_Pulse_Project_/blob/main/1_Retail_data_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
import pandas as pd
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')
# Getting access
# from google.colab import drive
# drive.mount('/content/drive')

In [117]:
url = "https://raw.githubusercontent.com/katiyardivyanshu08-bit/Retail_Pulse_Project_/main/Data/RetailPulse_500000_rows.csv"
df = pd.read_csv(url)
df.shape #(500000, 13)
df.head(10)
df.tail()
df.sample(10)

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
263525,142406,27,Female,North,Home & Kitchen,92109.90,23.0,27049.97,2025-12-29,13.08,0.2019,0.0556,Premium
311767,396647,28,Male,Central,Clothing,51344.88,21.0,25642.16,2025-12-30,7.82,0.3474,0.1056,Premium
47525,569965,52,Female,South,Beauty,65982.76,15.0,20244.10,2025-12-29,3.94,0.2971,0.0828,Premium
468552,576548,39,Male,Central,Grocery,25486.98,3.0,2136.72,2025-07-02,0.46,0.5079,0.1197,Budget
257551,587263,28,Male,North,Home & Kitchen,59194.29,3.0,10618.02,2025-08-25,2.87,NaN,0.0532,Budget
437223,176743,37,Male,West,Beauty,83955.10,3.0,11181.87,2025-10-08,2.43,0.0736,0.0410,Regular
477949,368178,51,Male,North,Clothing,43437.89,21.0,21850.34,2025-12-30,3.38,0.3231,0.0826,Premium
155211,396982,53,Male,East,Electronics,80427.76,6.0,10589.00,2025-09-25,0.79,0.5414,0.1541,Regular
315496,581215,27,Female,South,Clothing,33043.48,3.0,4835.82,2025-11-19,3.28,0.3281,0.1467,Budget
147143,271083,46,Female,West,Electronics,64838.38,4.0,6523.23,2025-11-22,2.19,0.4262,0.1419,Regular

In [118]:
df["LastPurchaseDate"] = pd.to_datetime(
    df["LastPurchaseDate"], errors="coerce"
)

reference_date = pd.Timestamp("2025-12-31")

df["Recency"] = (
    reference_date - df["LastPurchaseDate"]
).dt.days

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            500000 non-null  int64
 1   Age                   500000 non-null  int64
 2   Gender                497001 non-null  object
 3   Region                496504 non-null  object
 4   ProductCategory       497001 non-null  object
 5   AnnualIncome          495002 non-null  float64
 6   PurchaseFrequency     495998 non-null  float64
 7   AnnualPurchaseAmount  500000 non-null  float64
 8   LastPurchaseDate      500000 non-null  datetime64[ns]
 9   CustomerTenure        500000 non-null  float64
 10  DiscountUsage         494997 non-null  float64
 11  ReturnRate            496500 non-null  float64
 12  CustomerSegment       500000 non-null  object
 13  Recency               500000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(3), object(4)
memory usage: 53.4+ MB

In [120]:
df.describe()

,CustomerID,Age,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,Recency
count,500000.000000,500000.000000,495002.000000,495998.000000,500000.000000,500000,500000.000000,494997.000000,496500.000000,500000.000000
mean,349499.546422,40.856144,67404.824695,8.596408,12884.542060,2025-11-01 10:31:07.564800256,4.243120,0.339433,0.085718,59.561718
min,100001.000000,18.000000,18000.000000,1.000000,565.000000,2024-12-31 00:00:00,0.250000,0.005100,0.000000,1.000000
25%,224736.750000,32.000000,43434.195000,5.000000,6763.360000,2025-10-15 00:00:00,2.270000,0.187200,0.049700,19.000000
50%,349483.500000,40.000000,60097.425000,7.000000,10392.100000,2025-11-21 00:00:00,3.700000,0.309500,0.075800,40.000000
75%,474260.250000,49.000000,83034.477500,11.000000,16047.522500,2025-12-12 00:00:00,5.640000,0.466800,0.111600,77.000000
max,599000.000000,70.000000,350000.000000,55.000000,316973.080000,2025-12-30 00:00:00,14.800000,0.980000,0.524700,365.000000
std,144051.571449,11.756830,34246.285517,5.554789,9422.420371,NaN,2.646383,0.190285,0.049652,63.146612

In [121]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Region', 'ProductCategory',
       'AnnualIncome', 'PurchaseFrequency', 'AnnualPurchaseAmount',
       'LastPurchaseDate', 'CustomerTenure', 'DiscountUsage', 'ReturnRate',
       'CustomerSegment', 'Recency'],
      dtype='object')

In [122]:
num=df.select_dtypes(include="number").columns
cat=df.select_dtypes(include="object").columns
print(num)
print(cat)

Index(['CustomerID', 'Age', 'AnnualIncome', 'PurchaseFrequency',
       'AnnualPurchaseAmount', 'CustomerTenure', 'DiscountUsage', 'ReturnRate',
       'Recency'],
      dtype='object')
Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

**Numerical Column**

In [123]:
# df.isnull().mean()*100
df.select_dtypes(include="number").isnull().sum()

CustomerID                 0
Age                        0
AnnualIncome            4998
PurchaseFrequency       4002
AnnualPurchaseAmount       0
CustomerTenure             0
DiscountUsage           5003
ReturnRate              3500
Recency                    0
dtype: int64

In [124]:
null_count=df.select_dtypes(include=["number"]).isnull().sum()
null_count[null_count>0]

AnnualIncome         4998
PurchaseFrequency    4002
DiscountUsage        5003
ReturnRate           3500
dtype: int64

**Categorical**

In [125]:
cat

Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

In [126]:
df.select_dtypes(include="object").isnull().sum()

Gender             2999
Region             3496
ProductCategory    2999
CustomerSegment       0
dtype: int64

In [127]:
null_count=df.select_dtypes(include=["object"]).isnull().sum()
null_count[null_count>0]

Gender             2999
Region             3496
ProductCategory    2999
dtype: int64

In [128]:
df["Gender"].unique()

array(['Male', 'Female', nan, 'Other'], dtype=object)

In [129]:
for col in cat:
    df[col] = df[col].str.strip().str.lower()

In [130]:
df["Gender"] = df["Gender"].replace("other", "unknown")

In [131]:
df["Region"].unique()

array(['north', 'east', 'central', 'south', 'west', nan], dtype=object)

In [132]:
df["ProductCategory"].unique()

array(['beauty', 'clothing', 'electronics', 'home & kitchen', 'grocery',
       'sports', nan, 'home and kitchen'], dtype=object)

In [133]:
df["ProductCategory"] = df["ProductCategory"].replace({
    "home and kitchen": "home & kitchen"
})

In [134]:
df["CustomerSegment"].unique()

array(['regular', 'budget', 'premium'], dtype=object)

**Duplicate**

In [135]:
# df.duplicated().sum()  #1000
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499000 entries, 0 to 498999
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            499000 non-null  int64
 1   Age                   499000 non-null  int64
 2   Gender                496006 non-null  object
 3   Region                495507 non-null  object
 4   ProductCategory       496006 non-null  object
 5   AnnualIncome          494010 non-null  float64
 6   PurchaseFrequency     495008 non-null  float64
 7   AnnualPurchaseAmount  499000 non-null  float64
 8   LastPurchaseDate      499000 non-null  datetime64[ns]
 9   CustomerTenure        499000 non-null  float64
 10  DiscountUsage         494010 non-null  float64
 11  ReturnRate            495507 non-null  float64
 12  CustomerSegment       499000 non-null  object
 13  Recency               499000 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(3), object(4)
memory usage: 53.3+ MB

In [137]:
df

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment,Recency
0,204242,50,male,north,beauty,57328.90,4.0,10206.51,2025-09-07,3.16,0.3790,0.0929,regular,115
1,299677,36,male,east,clothing,66674.05,1.0,5497.05,2025-11-05,7.11,0.2153,0.0251,regular,56
2,240200,37,male,central,electronics,39673.95,2.0,5850.72,2025-10-20,6.43,0.1474,0.1273,budget,72
3,232815,36,male,south,clothing,70271.46,11.0,10174.37,2025-12-01,2.50,0.1379,0.0133,regular,30
4,508698,30,female,west,home & kitchen,67653.56,6.0,10441.58,2025-12-30,3.21,0.0958,0.0853,regular,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498995,359179,49,male,east,home & kitchen,64805.16,7.0,8624.35,2025-11-06,2.85,0.3288,0.1329,regular,55
498996,465839,33,male,central,electronics,100903.39,4.0,10645.11,2025-10-26,5.34,0.1384,0.0431,regular,66
498997,231933,33,male,central,home & kitchen,46207.75,7.0,9266.84,2025-12-30,9.19,0.5072,0.0686,regular,1
498998,246868,51,male,south,home & kitchen,36892.09,3.0,4569.21,2025-10-26,5.49,0.3177,0.1984,regular,66
498999,221959,29,female,south,beauty,84832.95,5.0,9945.71,2024-12-31,2.97,0.0733,0.0344,budget,365

In [138]:
# df.to_csv("Main_Clean.csv", index=False)