<a href="https://colab.research.google.com/github/katiyardivyanshu08-bit/Retail_Pulse_Project_/blob/main/1_Retail_data_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
import pandas as pd
import numpy as np
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')
# Getting access
# from google.colab import drive
# drive.mount('/content/drive')

In [152]:
url = "https://raw.githubusercontent.com/katiyardivyanshu08-bit/Retail_Pulse_Project_/main/Data/RetailPulse_500000_rows.csv"
df = pd.read_csv(url)
df.head(10)
df.shape #(500000, 13)
df.tail()
df.sample(10)

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
60216,547649,48,Female,South,Grocery,149077.00,8.0,21025.89,2025-07-03,3.71,0.0914,0.0580,Regular
74129,383736,27,Female,South,Electronics,92782.72,8.0,15371.85,2025-10-14,11.31,0.4885,0.0557,Regular
176549,174189,53,Female,South,Electronics,47048.47,5.0,6047.90,2025-10-02,4.20,0.5690,0.0905,Budget
440793,137433,31,Male,South,Clothing,18850.09,2.0,2174.19,2025-12-01,3.56,0.8272,0.1185,Budget
73520,577232,62,NaN,East,Sports,74806.01,6.0,14350.23,2025-11-08,7.00,0.3914,0.0909,Regular
213263,160762,47,Male,North,Grocery,42675.33,13.0,15211.63,2025-07-12,3.95,0.6509,0.1692,Regular
412701,551963,68,Female,South,Electronics,NaN,3.0,13739.04,2025-11-01,5.44,0.2928,0.0888,Regular
431814,440808,32,Female,South,Electronics,111858.99,35.0,32190.17,2025-12-29,5.45,0.6246,0.1062,Premium
148740,278562,28,Female,Central,Home & Kitchen,102965.91,15.0,15946.22,2025-12-19,4.28,0.3008,0.1806,Premium
419958,208584,39,Female,West,Grocery,NaN,9.0,18936.94,2025-11-21,4.52,0.1956,0.0747,Regular

In [153]:
df["LastPurchaseDate"] = pd.to_datetime(
    df["LastPurchaseDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            500000 non-null  int64
 1   Age                   500000 non-null  int64
 2   Gender                497001 non-null  object
 3   Region                496504 non-null  object
 4   ProductCategory       497001 non-null  object
 5   AnnualIncome          495002 non-null  float64
 6   PurchaseFrequency     495998 non-null  float64
 7   AnnualPurchaseAmount  500000 non-null  float64
 8   LastPurchaseDate      500000 non-null  datetime64[ns]
 9   CustomerTenure        500000 non-null  float64
 10  DiscountUsage         494997 non-null  float64
 11  ReturnRate            496500 non-null  float64
 12  CustomerSegment       500000 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 49.6+ MB

In [155]:
df.describe()

,CustomerID,Age,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate
count,500000.000000,500000.000000,495002.000000,495998.000000,500000.000000,500000,500000.000000,494997.000000,496500.000000
mean,349499.546422,40.856144,67404.824695,8.596408,12884.542060,2025-11-01 10:31:07.564800256,4.243120,0.339433,0.085718
min,100001.000000,18.000000,18000.000000,1.000000,565.000000,2024-12-31 00:00:00,0.250000,0.005100,0.000000
25%,224736.750000,32.000000,43434.195000,5.000000,6763.360000,2025-10-15 00:00:00,2.270000,0.187200,0.049700
50%,349483.500000,40.000000,60097.425000,7.000000,10392.100000,2025-11-21 00:00:00,3.700000,0.309500,0.075800
75%,474260.250000,49.000000,83034.477500,11.000000,16047.522500,2025-12-12 00:00:00,5.640000,0.466800,0.111600
max,599000.000000,70.000000,350000.000000,55.000000,316973.080000,2025-12-30 00:00:00,14.800000,0.980000,0.524700
std,144051.571449,11.756830,34246.285517,5.554789,9422.420371,NaN,2.646383,0.190285,0.049652

In [156]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Region', 'ProductCategory',
       'AnnualIncome', 'PurchaseFrequency', 'AnnualPurchaseAmount',
       'LastPurchaseDate', 'CustomerTenure', 'DiscountUsage', 'ReturnRate',
       'CustomerSegment'],
      dtype='object')

In [157]:
num=df.select_dtypes(include="number").columns
cat=df.select_dtypes(include="object").columns
print(num)
print(cat)

Index(['CustomerID', 'Age', 'AnnualIncome', 'PurchaseFrequency',
       'AnnualPurchaseAmount', 'CustomerTenure', 'DiscountUsage',
       'ReturnRate'],
      dtype='object')
Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

**Numerical Column**

In [158]:
# df.isnull().mean()*100
df.select_dtypes(include="number").isnull().sum()

CustomerID                 0
Age                        0
AnnualIncome            4998
PurchaseFrequency       4002
AnnualPurchaseAmount       0
CustomerTenure             0
DiscountUsage           5003
ReturnRate              3500
dtype: int64

In [159]:
null_count=df.select_dtypes(include=["number"]).isnull().sum()
null_count[null_count>0]

AnnualIncome         4998
PurchaseFrequency    4002
DiscountUsage        5003
ReturnRate           3500
dtype: int64

In [160]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# num_cols = [
#     "AnnualIncome",
#     "PurchaseFrequency",
#     "DiscountUsage",
#     "ReturnRate"
# ]

# plt.figure(figsize=(12, 8))

# for i, col in enumerate(num_cols, 1):
#     plt.subplot(2, 2, i)
#     sns.boxplot(y=df[col])
#     plt.title(f"Boxplot of {col}")

# plt.tight_layout()
# plt.show()

In [161]:
# num_cols = [
#     "AnnualIncome",
#     "PurchaseFrequency",
#     "DiscountUsage",
#     "ReturnRate"
# ]

# for col in num_cols:
#     df[col] = df[col].fillna(df[col].median())

In [162]:
# # Create AgeGroup feature
# df["AgeGroup"] = pd.cut(
#     df["Age"],
#     bins=[0, 25, 35, 50, 100],
#     labels=["18-25", "26-35", "36-50", "50+"],
#     include_lowest=True
# )

# # Check the new feature
# print(df[["Age", "AgeGroup"]].head())
# print(df["AgeGroup"].value_counts(dropna=False).sort_index())

In [163]:
df

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
0,204242,50,Male,North,Beauty,57328.90,4.0,10206.51,2025-09-07,3.16,0.3790,0.0929,Regular
1,299677,36,Male,East,Clothing,66674.05,1.0,5497.05,2025-11-05,7.11,0.2153,0.0251,Regular
2,240200,37,Male,Central,Electronics,39673.95,2.0,5850.72,2025-10-20,6.43,0.1474,0.1273,Budget
3,232815,36,Male,South,Clothing,70271.46,11.0,10174.37,2025-12-01,2.50,0.1379,0.0133,Regular
4,508698,30,Female,West,Home & Kitchen,67653.56,6.0,10441.58,2025-12-30,3.21,0.0958,0.0853,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,359179,49,Male,East,Home & Kitchen,64805.16,7.0,8624.35,2025-11-06,2.85,0.3288,0.1329,Regular
499996,465839,33,Male,Central,Electronics,100903.39,4.0,10645.11,2025-10-26,5.34,0.1384,0.0431,Regular
499997,231933,33,Male,Central,Home and Kitchen,46207.75,7.0,9266.84,2025-12-30,9.19,0.5072,0.0686,Regular
499998,246868,51,Male,South,Home & Kitchen,36892.09,3.0,4569.21,2025-10-26,5.49,0.3177,0.1984,Regular
499999,221959,29,Female,South,Beauty,84832.95,5.0,9945.71,2024-12-31,2.97,0.0733,0.0344,Budget

**Categorical**

In [164]:
cat

Index(['Gender', 'Region', 'ProductCategory', 'CustomerSegment'], dtype='object')

In [165]:
df.select_dtypes(include="object").isnull().sum()

Gender             2999
Region             3496
ProductCategory    2999
CustomerSegment       0
dtype: int64

In [166]:
null_count=df.select_dtypes(include=["object"]).isnull().sum()
null_count[null_count>0]

Gender             2999
Region             3496
ProductCategory    2999
dtype: int64

In [167]:
df["Gender"].unique()

array(['Male', 'Female', nan, 'Other'], dtype=object)

In [168]:
for col in cat:
    df[col] = df[col].str.strip().str.lower()

In [169]:
df["Gender"] = df["Gender"].replace("other", "unknown")

In [170]:
df["Region"].unique()

array(['north', 'east', 'central', 'south', 'west', nan], dtype=object)

In [171]:
df["ProductCategory"].unique()

array(['beauty', 'clothing', 'electronics', 'home & kitchen', 'grocery',
       'sports', nan, 'home and kitchen'], dtype=object)

In [172]:
df["ProductCategory"] = df["ProductCategory"].replace({
    "home and kitchen": "home & kitchen"
})

In [173]:
df["CustomerSegment"].unique()

array(['regular', 'budget', 'premium'], dtype=object)

In [174]:
# for col in cat:
#     df[col] = df[col].fillna("unknown")

In [175]:
# df["LastPurchaseDate"].dtype

In [176]:
# reference_date = pd.Timestamp("2025-12-31")
# df["Recency"] = (
#     reference_date - df["LastPurchaseDate"]
# ).dt.days
# df.drop("LastPurchaseDate", axis=1, inplace=True)

In [177]:
# df["Recency"].sample(5)

**Duplicate**

In [178]:
# df.duplicated().sum()  #1000
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499000 entries, 0 to 498999
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CustomerID            499000 non-null  int64
 1   Age                   499000 non-null  int64
 2   Gender                496006 non-null  object
 3   Region                495507 non-null  object
 4   ProductCategory       496006 non-null  object
 5   AnnualIncome          494010 non-null  float64
 6   PurchaseFrequency     495008 non-null  float64
 7   AnnualPurchaseAmount  499000 non-null  float64
 8   LastPurchaseDate      499000 non-null  datetime64[ns]
 9   CustomerTenure        499000 non-null  float64
 10  DiscountUsage         494010 non-null  float64
 11  ReturnRate            495507 non-null  float64
 12  CustomerSegment       499000 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 49.5+ MB

In [180]:
df

,CustomerID,Age,Gender,Region,ProductCategory,AnnualIncome,PurchaseFrequency,AnnualPurchaseAmount,LastPurchaseDate,CustomerTenure,DiscountUsage,ReturnRate,CustomerSegment
0,204242,50,male,north,beauty,57328.90,4.0,10206.51,2025-09-07,3.16,0.3790,0.0929,regular
1,299677,36,male,east,clothing,66674.05,1.0,5497.05,2025-11-05,7.11,0.2153,0.0251,regular
2,240200,37,male,central,electronics,39673.95,2.0,5850.72,2025-10-20,6.43,0.1474,0.1273,budget
3,232815,36,male,south,clothing,70271.46,11.0,10174.37,2025-12-01,2.50,0.1379,0.0133,regular
4,508698,30,female,west,home & kitchen,67653.56,6.0,10441.58,2025-12-30,3.21,0.0958,0.0853,regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...
498995,359179,49,male,east,home & kitchen,64805.16,7.0,8624.35,2025-11-06,2.85,0.3288,0.1329,regular
498996,465839,33,male,central,electronics,100903.39,4.0,10645.11,2025-10-26,5.34,0.1384,0.0431,regular
498997,231933,33,male,central,home & kitchen,46207.75,7.0,9266.84,2025-12-30,9.19,0.5072,0.0686,regular
498998,246868,51,male,south,home & kitchen,36892.09,3.0,4569.21,2025-10-26,5.49,0.3177,0.1984,regular
498999,221959,29,female,south,beauty,84832.95,5.0,9945.71,2024-12-31,2.97,0.0733,0.0344,budget

In [181]:
df.to_csv("After_clean_retailpulse.csv", index=False)